### ISSUE TITLE
terminationGracePeriodSeconds works with nanoserver based container images but not servercore based images

### ISSUE THREAD

**Issue by marosset** [microsoft/Windows-Containers#164]
Delayed app shutdown / terminationGracePeriod appear to only work with contianer images based on nanoserver.

I am experimenting with the `terminationGracePeriodSeconds' for Windows container applications and have observed that this functionally works as expected if the container images are based on nanoserver but do not behave as expected if the container images are based on servercore.

I have a kubernetes `v1.23.0-alpha.2` cluster with Windows Server 2019 nodes running containerd `v1.5.4`.

If I deploy the following pod to the cluster which runs this application https://github.com/marosset/windows-container-graceful-shutdown/blob/master/dotnet/Program.cs 

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delayed-shutdown
  labels:
    app: delated-shutdown
spec:  
  replicas: 1
  template:
    metadata:
      name: delayed-shutdown
      labels:
        app: delayed-shutdown
    spec:
      containers:
      - name: delayed-shutdown
        image: mrosse3/delayed-shutdown-dotnet:5.0-nanoserver
        imagePullPolicy: Always
      terminationGracePeriodSeconds: 75
      nodeSelector:
        "kubernetes.io/os": windows
  selector:
    matchLabels:
      app: delayed-shutdown
```

If I follow the logs of one of the containers with `kubectl logs -f {pod name}` and then scale down the deployment or delete the pod I see

```cmd
Waiting for control event...
CTRL_SHUTDOWN received
Exiting in 60 seconds...
60
59
58
<snip>
4
3
2
1
Goodbye
```

If I set terminationGracePeriodSeconds to less than 60 seconds I see the log messages stop at the appropriate time which indicates that everything is working as expected.

If I run the same application in a container image based on mcr.microsoft.com/dotnet/runtime:5.0-windowsservercore-ltsc2019 (available at mrosse3/delayed-shutdown-dotnet:5.0-servercore) and view logs as the pod is being stopped I only see the following before the container exits.

```cmd
Waiting for control event...
CTRL_SHUTDOWN received 
```

When I try this in an application written in golang (https://github.com/marosset/windows-container-graceful-shutdown/blob/master/go/delayed-shutdown.go) I see the same behavior (except that on servercore the container waits 5 seconds before exiting regardless of what the specified terminationGracePeriodSeconds is set to)
