### ISSUE TITLE
unstable networking latency from within pods running on a Windows Server 2004 node

### ISSUE THREAD

**Issue by singholt** [microsoft/Windows-Containers#178]
Hi,
I have a Kubernetes cluster with version 1.21. I have setup 1 Windows 2004 node and 1 Linux node in the cluster. I have the following deployment with 4 pods running on the Windows 2004 node.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows-servercore-webserver-2004
spec:
  selector:
    matchLabels:
      app: windows-servercore-webserver-2004
      tier: backend
      track: stable
  replicas: 4
  template:
    metadata:
      labels:
        app: windows-servercore-webserver-2004
        tier: backend
        track: stable
    spec:
      containers:
      - name: windows-servercore-webserver-2004
        image: mcr.microsoft.com/windows/servercore:2004
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
        command:
        - powershell.exe
        - -command
        - "<#code used from https://gist.github.com/wagnerandrade/5424431#> ; $$listener = New-Object System.Net.HttpListener ; $$listener.Prefixes.Add('http://*:80/') ; $$listener.Start() ; $$callerCounts = @{} ; Write-Host('Listening at http://*:80/') ; while ($$listener.IsListening) { ;$$context = $$listener.GetContext() ;$$requestUrl = $$context.Request.Url ;$$clientIP = $$context.Request.RemoteEndPoint.Address ;$$response = $$context.Response ;Write-Host '' ;Write-Host('> {0}' -f $$requestUrl) ;  ;$$count = 1 ;$$k=$$callerCounts.Get_Item($$clientIP) ;if ($$k -ne $$null) { $$count += $$k } ;$$callerCounts.Set_Item($$clientIP, $$count) ;$$ip=(Get-NetAdapter | Get-NetIpAddress); $$header='<html><body><H1>Windows Container Web Server</H1>' ;$$callerCountsString='' ;$$callerCounts.Keys | % { $$callerCountsString+='<p>IP {0} callerCount {1} ' -f $$ip[1].IPAddress,$$callerCounts.Item($$_) } ;$$footer='</body></html>' ;$$content='{0}{1}{2}' -f $$header,$$callerCountsString,$$footer ;Write-Output $$content ;$$buffer = [System.Text.Encoding]::UTF8.GetBytes($$content) ;$$response.ContentLength64 = $$buffer.Length ;$$response.OutputStream.Write($$buffer, 0, $$buffer.Length) ;$$response.Close() ;$$responseStatus = $$response.StatusCode ;Write-Host('< {0}' -f $$responseStatus)  } ; "
      nodeSelector:
        beta.kubernetes.io/os: windows
        beta.kubernetes.io/arch: amd64
---
apiVersion: v1
kind: Service
metadata:
  name: windows-servercore-webserver-service-2004
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: windows-servercore-webserver-2004
    tier: backend
    track: stable
  sessionAffinity: None
  type: ClusterIP
```

I'm seeing network latency from within the pods when trying to ping endpoints like www.google.com.

Repro: 
exec into each of the 4 pods and run:
```
kubectl exec -it <pod> powershell

Invoke-WebRequest -Uri https://download.elifulkerson.com//files/tcping/0.39/tcping.exe -OutFile tcping.exe

.\tcping.exe -t -p 443 www.google.com
```

<img width="714" alt="image" src="https://user-images.githubusercontent.com/60409639/140203730-a219ce90-35a0-4504-a581-8e9e6fd35b3d.png">

Notice the "No response" with time > 2000ms.

This setup is on AWS EKS with DSR mode enabled on the 2004 node.

Couple of observations:
- The issue still persists even with DSR mode disabled on the node.
- Running docker containers and running the same experiment does not seem to have the network timeout issue. This tells me there could be something going on with the kubernetes components (kubelet/kube-proxy).
- Running the same experiment of WS 2019 does not seem to cause issues either.
