### ISSUE TITLE
Writes to emptyDir is much slower as compared to writes within container root fs

### ISSUE THREAD

**Issue by ibabou** [microsoft/Windows-Containers#345]
**Describe the bug**
We have been doing perf testing as complains arose around slower writes when writing to emptyDir. Based on the experiments, we can see that it's definitely slower especially with large sets of small files (like cloning a repo for example).

**To Reproduce** 
Those tests were ran on GKE clusters, but the results will be identical to OSS clusters with GCE provider. We've looked into the perf. of backing managed boot-disk, and there wasn't any overhead or throttling happening. the tests were made on regular disks as well as using higher perf disks (pd-ssd), and the slowness still remains as compared to writes within container FS.

**Expected behavior**
We expect a similar performance with the writes to emptyDir.

Example for a test container:
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-empty-dir
spec:
 containers:
 - args:
   - netexec
   image: k8s.gcr.io/e2e-test-images/agnhost:2.20
   name: agnhost
   imagePullPolicy: IfNotPresent
   ports:
   - containerPort: 8080
   volumeMounts:
    - mountPath: "C:\\test-ssd"
      name: "test-ssd-empty-dir"
    - mountPath: "C:\\anotherdir_mount"
      name: another-dir
      readOnly: false
 nodeSelector:
  kubernetes.io/os: windows
 volumes:
  - name: test-ssd-empty-dir
    emptyDir: {}
  - name: another-dir
    hostPath:
      path: "C:\\anotherdir"
```

Test 1: emtyDir vs container fs (high perf  disk - cloning a repo - 300% slower):

```
C:/test-ssd $ powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\test-ssd> Measure-Command {git clone https://github.com/openjdk/jdk}
Cloning into 'jdk'...
remote: Enumerating objects: 1346798, done.
remote: Counting objects: 100% (478/478), done.
remote: Compressing objects: 100% (309/309), done.
Receiving objects: 100% (1346798/1346798), 1.06 GiB | 17.64 MiB/s, done.346320

Resolving deltas: 100% (1000847/1000847), done.
Updating files: 100% (66565/66565), done.


Days              : 0
Hours             : 0
Minutes           : 15
Seconds           : 53
Milliseconds      : 518
Ticks             : 9535184729
TotalDays         : 0.0110360934363426
TotalHours        : 0.264866242472222
TotalMinutes      : 15.8919745483333
TotalSeconds      : 953.5184729
TotalMilliseconds : 953518.4729


PS C:\> Measure-Command {git clone https://github.com/openjdk/jdk}
Cloning into 'jdk'...
remote: Enumerating objects: 1346813, done.
remote: Counting objects: 100% (528/528), done.
remote: Compressing objects: 100% (332/332), done.
Receiving objects: 100% (1346813/1346813), 1.06 GiB | 17.66 MiB/s, done.346285

Resolving deltas: 100% (1000206/1000206), done.
Updating files: 100% (66565/66565), done.


Days              : 0
Hours             : 0
Minutes           : 3
Seconds           : 56
Milliseconds      : 546
Ticks             : 2365465153
TotalDays         : 0.0027378068900463
TotalHours        : 0.0657073653611111
TotalMinutes      : 3.94244192166667
TotalSeconds      : 236.5465153
TotalMilliseconds : 236546.5153
```

Test 2: emtyDir vs container fs (high perf  disk - cloning a repo - ~57% slower):

```
PS C:\test-ssd> Measure-Command {1..10000 | %{ ($_ * (Get-Random -Max ([int]::maxvalue))) > "file$_.txt"}}


Days              : 0
Hours             : 0
Minutes           : 1
Seconds           : 57
Milliseconds      : 174
Ticks             : 1171741456
TotalDays         : 0.00135618224074074
TotalHours        : 0.0325483737777778
TotalMinutes      : 1.95290242666667
TotalSeconds      : 117.1741456
TotalMilliseconds : 117174.1456

PS C:\> Measure-Command {1..10000 | %{ ($_ * (Get-Random -Max ([int]::maxvalue))) > "file$_.txt"}}


Days              : 0
Hours             : 0
Minutes           : 1
Seconds           : 15
Milliseconds      : 466
Ticks             : 754661779
TotalDays         : 0.000873451133101852
TotalHours        : 0.0209628271944444
TotalMinutes      : 1.25776963166667
TotalSeconds      : 75.4661779
TotalMilliseconds : 75466.1779
```

Test 3 : container fs with symlink vs emptyDir (this was to check if symlink overhead could be the cause - still ~46% slower):

```
PS C:\test> mkdir src
PS C:\test> New-Item -Path C:\test\sym -ItemType SymbolicLink -Value C:\test\src
PS C:\test> cd sym
PS C:\test\sym> Measure-Command {1..10000 | %{ ($_ * (Get-Random -Max ([int]::maxvalue))) > "file$_.txt"}}
 
 
Days              : 0
Hours             : 0
Minutes           : 1
Seconds           : 32
Milliseconds      : 173
Ticks             : 921737106
TotalDays         : 0.00106682535416667
TotalHours        : 0.0256038085
TotalMinutes      : 1.53622851
TotalSeconds      : 92.1737106
TotalMilliseconds : 92173.7106
 
 
PS C:\emptydir> Measure-Command {1..10000 | %{ ($_ * (Get-Random -Max ([int]::maxvalue))) > "file$_.txt"}}
 
 
Days              : 0
Hours             : 0
Minutes           : 2
Seconds           : 13
Milliseconds      : 681
Ticks             : 1336813105
TotalDays         : 0.0015472373900463
TotalHours        : 0.0371336973611111
TotalMinutes      : 2.22802184166667
TotalSeconds      : 133.6813105
TotalMilliseconds : 133681.3105
```

**Configuration:**
 - Edition: Windows Server 2019 LTSC
- Base Image being used: Windows Server Core
 - Container engine: containerd
 - Container Engine version: 1.6.13

**Additional context**
