### ISSUE TITLE
available containers for my system

### ISSUE THREAD

**Issue by borhae** [microsoft/Windows-Containers#349]
I'm trying to create the following image:
```
FROM mcr.microsoft.com/windows/server:XXX

RUN powershell -Command \
    Install-WindowsFeature BranchCache -IncludeManagementTools ; \
    Remove-Item -Recurse C:\Windows\Logs\CBS

CMD [ "powershell" ]
```
But regardless what tag I'm trying to use (from the list available at https://hub.docker.com/_/microsoft-windows-server) , after 
```
docker build -t image:v1
```
I always get either 
```
a Windows version XXX-based image is incompatible with a 10.0.19044 host
```
or 
```
no matching manifest for windows/amd64 10.0.19044 in the manifest list entries
```
If I use the mcr.microsoft.com/windows/servercore:ltsc2019 image, I get the following error
```
Install-WindowsFeature : The request to add or remove features on the 
specified server failed.
Installation of one or more roles, role services, or features failed.
The source files could not be found.
```
Is this not meant to work or am I doing it wrong?

**Comment by vrapolinario** [comment]
Can you please confirm you are using a Windows 10 host? That would explain the issue. Also, how did you get the other imagento run (docker pull and run command)?

I believe the binaries ot this feature were removed in Server Core as it's a Server role. You would have to use the Server image instead.

**Comment by borhae** [comment]
I can confirm that I'm using a windows 10 host (Version 21H2 (Build 19044..2728). 
As you expected I got the other image running with docker pull mcr.microsoft.com/windows/servercore:ltsc2019. From then on I used docker compose with (docker-compose.yaml)
```
services:
  server:
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    command: powershell ./app/script.ps1
    ports:
      - "8080:80"
    volumes:
      - .\serverfiles:c:\app
  client1:
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    # Add any necessary environment variables or ports for the client
    volumes:
      - .\clientfiles:c:\scripts
    command: cmd /c "c:\\scripts\\script.bat"
  client2:
    ... same as client1
```
and then
```
docker compose up
```
On a different windows 10 machine I didn't need the pull, but was just including the part in the docker-compose.yaml file. What I did need to do, was switching to windows containers in docker desktop. 
Is there any workaround to get the BranchCache Feature running for docker containers running on a windows 10 host? 
I would like to test out how the peer 2 peer install of BITS performs. We have a very large client that needs to be installed on a large amount of machines that are often sitting behind networks that can access the internet only with small data rates.
