### ISSUE TITLE
Fatal SSL errors occur in some applications unless curl is run inside the container, whose side effects somehow resolve the issue

### ISSUE THREAD

**Issue by doctorpangloss** [microsoft/Windows-Containers#503]
**Describe the bug**
There is a surprising interaction between the way certificates are configured on Windows Containers; the differences between how Docker Desktop / dockerd.exe and Kubernetes mount (or do not mount) host certificates onto containers; and various workarounds that Windows applications do to work around certificate issues.

The net result is that a fatal SSL occur will occur always in a production Kubernetes cluster, unless some other side-effect-causing command resolves the issue.

**To Reproduce** 
In a `mcr.microsoft.com/windows/servercore:10.0.20348.1970` image:

```
FROM mcr.microsoft.com/windows/servercore:10.0.20348.1970 as build
USER ContainerAdministrator

ARG PIP_DISABLE_PIP_VERSION_CHECK=1
ARG PIP_NO_CACHE_DIR=1

RUN powershell -NoProfile -ExecutionPolicy Bypass -Command "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))"
RUN choco install -y python --version=3.11.9
RUN pip install fsspec

FROM mcr.microsoft.com/windows/servercore:10.0.20348.1970 as final
USER ContainerAdministrator
COPY --link --from=build C:/Python311 C:/Python311
SHELL ["cmd", "/S", "/C"]
RUN setx /M PATH "%PATH%;C:\Python311;C:\Python311\Scripts"
```

Python has now been copied into the image with no side effects.

```
import fsspec

url = 'https://fastly.picsum.photos/id/269/536/354.jpg?hmac=LprBr5lQFyGBvbqcZYCZ6hoF4eJ_hfCEplsS2XSFOhY'
file_name = 'image.jpg'

with fsspec.open(url, mode='rb') as f:
    with open(file_name, 'wb') as file:
        file.write(f.read())
```

will cause the error

```
raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host fastly.picsum.photos:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]
```

If I run
```
curl -I https://upload.wikimedia.org/wikipedia/commons/c/c9/Rainbow-diagram-ROYGBIV.svg
```
i.e., curl an unrelated URL, but **not** https://www.google.com, the error goes away.

This also reproduced when the `reloadium` python package was installed during a Docker build, which is probably related to `pip_system_certs` causing this issue to occur earlier. It wasn't essential that Python was installed by copying in this case, it occurred in the build image.

**Expected behavior**
Fatal SSL errors should not occur unexpectedly.

**Configuration:**
 - Edition: Windows 2022 LTSC
- Base Image being used: Windows Server Core
 - Container engine:

Docker Desktop test:
```
Client:
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Fri Feb 23 02:40:51 2024
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.28.0 (139021)
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 20:55:49 2024
  OS/Arch:          windows/amd64
  Experimental:     false
```
Kubernetes test:
```
clientVersion:
  buildDate: "2023-06-14T09:53:42Z"
  compiler: gc
  gitCommit: 25b4e43193bcda6c7328a6d147b1fb73a33f1598
  gitTreeState: clean
  gitVersion: v1.27.3
  goVersion: go1.20.5
  major: "1"
  minor: "27"
  platform: windows/amd64
kustomizeVersion: v5.0.1
serverVersion:
  buildDate: "2024-04-09T05:12:22Z"
  compiler: gc
  gitCommit: 1649f592f1909b97aa3c2a0a8f968a3fd05a7b8b
  gitTreeState: clean
  gitVersion: v1.26.15+k0s
  goVersion: go1.21.9
  major: "1"
  minor: "26"
  platform: linux/amd64
```

Test node:

```
System Info:
  Machine ID:                                AppMana-xxx
  System UUID:                               7x-xxx-xxx-xxx-x5
  Boot ID:                                   58
  Kernel Version:                            10.0.20348.1547
  OS Image:                                  Windows Server 2022 Datacenter
  Operating System:                          windows
  Architecture:                              amd64
  Container Runtime Version:                 containerd://1.7.17
  Kubelet Version:                           v1.26.2
  Kube-Proxy Version:                        v1.26.2
```
